# Generated by Django 4.2.4 on 2023-08-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='title',
        ),
    ]
